[package]
name = "scnr"
version = "0.1.0"
edition = "2021"
authors = ["Jörg Singer <singer.joerg@gmx.de>"]
description = "LL(k) and LALR(1) parser generator for Rust"
documentation = "https://docs.rs/scnr"
repository = "https://github.com/jsinger67/scnr"
readme = "README.md"
keywords = ["scanner", "lexer", "parsing", "lexing"]
categories = ["algorithms", "parsing", "Parsing tools"]
license = "MIT/Apache-2.0"

[dependencies]
dot-writer = "0.1.3"
log = "0.4.22"
regex-syntax = "0.8.4"
serde = { version = "1.0.207", features = ["derive"] }
serde_json = "1.0.125"
thiserror = "1.0.63"

[dev-dependencies]
criterion = "0.5.1"
env_logger = "0.11.5"
regex = "1.10.5"

[[bench]]
name = "scanner_benchmark"
harness = false

[profile.release]
debug = true
