[package]
name = "scnr"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
regex-syntax = "0.8.4"
thiserror = "1.0.63"

[dev-dependencies]
dot-writer = "0.1.3"
env_logger = "0.11.5"
regex = "1.10.5"
